/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};

/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {

/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId])
/******/ 			return installedModules[moduleId].exports;

/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			exports: {},
/******/ 			id: moduleId,
/******/ 			loaded: false
/******/ 		};

/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

/******/ 		// Flag the module as loaded
/******/ 		module.loaded = true;

/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}


/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;

/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;

/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";

/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(0);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
/***/ function(module, exports, __webpack_require__) {

	__webpack_require__(1)
	var __weex_template__ = __webpack_require__(5)
	var __weex_style__ = __webpack_require__(6)
	var __weex_script__ = __webpack_require__(7)

	__weex_define__('@weex-component/4aa9f4e2af5dcae48fedd2647ddc4828', [], function(__weex_require__, __weex_exports__, __weex_module__) {

	    __weex_script__(__weex_module__, __weex_exports__, __weex_require__)
	    if (__weex_exports__.__esModule && __weex_exports__.default) {
	      __weex_module__.exports = __weex_exports__.default
	    }

	    __weex_module__.exports.template = __weex_template__

	    __weex_module__.exports.style = __weex_style__

	})

	__weex_bootstrap__('@weex-component/4aa9f4e2af5dcae48fedd2647ddc4828',undefined,undefined)

/***/ },
/* 1 */
/***/ function(module, exports, __webpack_require__) {

	var __weex_template__ = __webpack_require__(2)
	var __weex_style__ = __webpack_require__(3)
	var __weex_script__ = __webpack_require__(4)

	__weex_define__('@weex-component/item', [], function(__weex_require__, __weex_exports__, __weex_module__) {

	    __weex_script__(__weex_module__, __weex_exports__, __weex_require__)
	    if (__weex_exports__.__esModule && __weex_exports__.default) {
	      __weex_module__.exports = __weex_exports__.default
	    }

	    __weex_module__.exports.template = __weex_template__

	    __weex_module__.exports.style = __weex_style__

	})


/***/ },
/* 2 */
/***/ function(module, exports) {

	module.exports = {
	  "type": "div",
	  "classList": [
	    "container"
	  ],
	  "events": {
	    "click": "onclickitem"
	  },
	  "children": [
	    {
	      "type": "text",
	      "classList": [
	        "tab-text"
	      ],
	      "style": {
	        "color": function () {return this.titleColor}
	      },
	      "attr": {
	        "value": function () {return this.title}
	      }
	    }
	  ]
	}

/***/ },
/* 3 */
/***/ function(module, exports) {

	module.exports = {
	  "container": {
	    "flex": 1,
	    "flexDirection": "column",
	    "alignItems": "center",
	    "justifyContent": "center",
	    "height": 70
	  },
	  "tab-text": {
	    "position": "absolute",
	    "left": 0,
	    "right": 0,
	    "top": 0,
	    "bottom": 0,
	    "marginTop": 15,
	    "textAlign": "center",
	    "fontSize": 28,
	    "fontWeight": "bold",
	    "borderBottomWidth": 2,
	    "borderColor": "rgb(247,206,70)"
	  }
	}

/***/ },
/* 4 */
/***/ function(module, exports) {

	module.exports = function(module, exports, __weex_require__){'use strict';

	module.exports = {
	  data: function () {return {
	    index: 0,
	    title: '待完成',
	    titleColor: 'grey'
	  }},
	  methods: {
	    onclickitem: function onclickitem(e) {
	      var vm = this;
	      var params = {
	        index: vm.index
	      };
	      vm.$dispatch('tabItem.onClick', params);
	    }
	  }
	};}
	/* generated by weex-loader */


/***/ },
/* 5 */
/***/ function(module, exports) {

	module.exports = {
	  "type": "div",
	  "children": [
	    {
	      "type": "div",
	      "style": {
	        "flexDirection": "row"
	      },
	      "children": [
	        {
	          "type": "div",
	          "classList": [
	            "grabview"
	          ],
	          "style": {
	            "borderColor": "rgb(239,135,50)"
	          },
	          "children": [
	            {
	              "type": "text",
	              "classList": [
	                "grabtext"
	              ],
	              "attr": {
	                "value": "抢单数"
	              }
	            },
	            {
	              "type": "text",
	              "classList": [
	                "grabtext"
	              ],
	              "attr": {
	                "value": function () {return this.getpass(this.row.task_capture)}
	              }
	            }
	          ]
	        },
	        {
	          "type": "div",
	          "classList": [
	            "grabview"
	          ],
	          "style": {
	            "borderColor": "rgb(247,206,70)"
	          },
	          "children": [
	            {
	              "type": "text",
	              "classList": [
	                "grabtext"
	              ],
	              "attr": {
	                "value": "成功率"
	              }
	            },
	            {
	              "type": "text",
	              "classList": [
	                "grabtext"
	              ],
	              "attr": {
	                "value": function () {return this.getpassrate(this.row.task_capture,this.row.task_pass)}
	              }
	            }
	          ]
	        }
	      ]
	    },
	    {
	      "type": "text",
	      "style": {
	        "backgroundColor": "rgb(235,235,235)",
	        "height": 66,
	        "textAlign": "center",
	        "paddingTop": 15,
	        "color": "rgb(85,85,85)"
	      },
	      "attr": {
	        "value": "我的任务"
	      }
	    },
	    {
	      "type": "div",
	      "style": {
	        "backgroundColor": "#FF0000"
	      }
	    },
	    {
	      "type": "div",
	      "classList": [
	        "wrapper"
	      ],
	      "children": [
	        {
	          "type": "div",
	          "classList": [
	            "tabbar"
	          ],
	          "append": "tree",
	          "children": [
	            {
	              "type": "item",
	              "repeat": function () {return this.tabItems},
	              "attr": {
	                "index": function () {return this.index},
	                "title": function () {return this.title},
	                "titleColor": function () {return this.titleColor}
	              }
	            }
	          ]
	        },
	        {
	          "type": "embed",
	          "classList": [
	            "content"
	          ],
	          "style": {
	            "visibility": function () {return this.visibility}
	          },
	          "repeat": function () {return this.tabItems},
	          "attr": {
	            "src": function () {return this.src},
	            "type": "weex"
	          }
	        }
	      ]
	    }
	  ]
	}

/***/ },
/* 6 */
/***/ function(module, exports) {

	module.exports = {
	  "grabview": {
	    "alignItems": "center",
	    "flexDirection": "column",
	    "marginTop": 8,
	    "borderBottomWidth": 4,
	    "flex": 1
	  },
	  "grabtext": {
	    "color": "#808080",
	    "size": 28,
	    "paddingBottom": 8
	  },
	  "wrapper": {
	    "width": 750,
	    "position": "absolute",
	    "top": 174,
	    "left": 0,
	    "right": 0,
	    "bottom": 0
	  },
	  "content": {
	    "position": "fixed",
	    "top": 244,
	    "left": 0,
	    "right": 0,
	    "bottom": 0,
	    "marginBottom": 0,
	    "backgroundColor": "#FFFFFF"
	  },
	  "tabbar": {
	    "flexDirection": "row",
	    "position": "fixed",
	    "top": 174,
	    "left": 0,
	    "right": 0,
	    "height": 70
	  }
	}

/***/ },
/* 7 */
/***/ function(module, exports, __webpack_require__) {

	module.exports = function(module, exports, __weex_require__){'use strict';

	__webpack_require__(1);
	var eventModule = __weex_require__('@weex-module/requestevent');
	var stream = __weex_require__('@weex-module/stream');

	module.exports = {
	  data: function () {return {
	    row: {},
	    tabItems: [{ index: 0,
	      title: '待完成',
	      titleColor: 'grey',
	      visibility: 'visible',
	      selectedColor: 'red',
	      src: 'http://exposs.oss-cn-hangzhou.aliyuncs.com/weex/ios/JS_138/mytasklist.js?sort=getUserTaskDoing'
	    }, { index: 1,
	      title: '待审核',
	      titleColor: 'grey',
	      visibility: 'hidden',
	      selectedColor: 'red',
	      src: 'http://exposs.oss-cn-hangzhou.aliyuncs.com/weex/ios/JS_138/mytasklist.js?sort=getUserTaskExamining'
	    }, { index: 2,
	      title: '已通过',
	      titleColor: 'grey',
	      visibility: 'hidden',
	      selectedColor: 'red',
	      src: 'http://exposs.oss-cn-hangzhou.aliyuncs.com/weex/ios/JS_138/mytasklist.js?sort=getUserTaskPass'
	    }, { index: 3,
	      title: '未通过',
	      titleColor: 'grey',
	      visibility: 'hidden',
	      selectedColor: 'red',
	      src: 'http://exposs.oss-cn-hangzhou.aliyuncs.com/weex/ios/JS_138/mytasklist.js?sort=getUserTaskUnpass'
	    }],
	    selectedIndex: 0,
	    selectedColor: 'red',
	    unselectedColor: 'grey'
	  }},
	  created: function created() {
	    this.selected(this.selectedIndex);

	    this.$on('tabItem.onClick', function (e) {
	      var detail = e.detail;
	      this.selectedIndex = detail.index;
	      this.selected(detail.index);

	      var params = {
	        index: detail.index
	      };
	    });

	    this.getlistrequest();
	  },
	  methods: {
	    selected: function selected(index) {
	      for (var i = 0; i < this.tabItems.length; i++) {
	        var tabItem = this.tabItems[i];
	        if (i == index) {
	          tabItem.titleColor = tabItem.selectedColor;
	          tabItem.visibility = 'visible';
	        } else {
	          tabItem.titleColor = this.unselectedColor;
	          tabItem.visibility = 'hidden';
	        }
	      }
	    },
	    getlistrequest: function getlistrequest() {

	      var self = this;
	      eventModule.getHomeDatas(function (ret) {
	        var GET_URL_List = ret.main_url + 'getUserTaskInfo';
	        var BODY_URL = 'user_id=' + ret.uid + '&sid=' + ret.sid + '&_t=' + ret._t + '&platform_id=' + ret.platform + '&version=' + ret.version + '&container_id=' + ret.container_id;

	        stream.fetch({
	          method: 'POST',
	          url: GET_URL_List,
	          body: BODY_URL,
	          type: 'json'
	        }, function (ret) {
	          if (!ret.ok) {} else {

	            var dic = ret.data;
	            self.row = dic;
	          }
	        }, function (response) {});
	      });
	    },

	    getpass: function getpass(task_capture) {
	      if (task_capture == 0) {
	        return '0';
	      } else {
	        return task_capture;
	      }
	    },
	    getpassrate: function getpassrate(task_capture, task_pass) {
	      if (task_capture == 0) {
	        return '0%';
	      } else {
	        var rate = task_pass * 100 / task_capture;
	        var rateint = parseInt(rate);
	        var cha = rate - rateint;
	        if (cha >= 0.5) {
	          rateint = rateint + 1;
	        }
	        return rateint + '%';
	      }
	    }
	  }
	};}
	/* generated by weex-loader */


/***/ }
/******/ ]);